name:                events-bot
version:             0.1.0.0
github:              "githubuser/events-bot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/events-bot#readme>

dependencies:
- base >= 4.7 && < 5
- discord-haskell
- text
- bytestring
- base64-bytestring
- mtl
- gogol-apps-calendar
- servant
- servant-client
- servant-server
- http-client
- http-client-tls
- gogol
- resourcet
- lens
- time
- rrule
- uri-encode

library:
  source-dirs: src

executables:
  events-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - events-bot

ghc-options:
  - -Wall

tests:
  events-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - events-bot
